WebApplication1/WebApplication1/Controllers/EasternConferenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class EasternConferenceController : Controller
    {
        // GET: EasternConference
        public ActionResult MainPage()
        {
            return View();
        }
    }
}

WebApplication1/WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        //Default page
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult NBA()
        {
            return Redirect("http://www.nba.com/");
        }
    }
}

WebApplication1/WebApplication1/Controllers/WesternConferenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class WesternConferenceController : Controller
    {
        // GET: WesternConference
        public ActionResult MainPage()
        {
            return View();
        }
    }
}

WebApplication1/WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication1/WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication1/WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>NBA</h1>
    <p class="lead">The National Basketball Association</p>
    <p><a href="http://www.espn.com/nba/" class="btn btn-primary btn-lg" target="_blank">NBA Home &raquo;</a></p>
</div>

<div class="row center-txt">
    <div class="col-md-4">
        <h2>Eastern Conference</h2>
        <p>The Kingdom of Lebron James</p>
        <a href="@Url.Action("MainPage", "EasternConference")">
            <img class="column4" src="~/Content/Images/Eastern_Conference_(NBA)_logo.gif" />
        </a>
    </div>
    <div class="col-md-4">
        <h2>Future Players</h2>
        <p>Speak with fellow fans about college stars, high-school sensations, and aspiring youth.</p>
        <a href="@Url.Action("MainPage", "FuturePlayers")">
            <img class="column4" src="~/Content/Images/NBA_Draft.jpeg" />
        </a>
    </div>
    <div class="col-md-4">
        <h2>Western Conference</h2>
        <p>All-Stars and Splash Bros.</p>
        <a href="@Url.Action("MainPage", "WesternConference")">
            <img class="column4" src="~/Content/Images/Western_Conference_(NBA)_logo.gif" />
        </a>
    </div>
</div>